
version: 1.13.{build}
pull_requests:
  do_not_increment_build_number: true
shallow_clone: true
environment:
  CMakeArgs: ""
  APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
  VCVER: 9.0
  ARCH: x86
install:
- cmd: appveyor DownloadFile https://github.com/ninja-build/ninja/releases/download/v1.9.0/ninja-win.zip -FileName ninja.zip
- cmd: 7z x ninja.zip
- cmd: set PATH=%cd%;%PATH%
- cmd: ninja --version
build_script:
- cmd: call "C:\Program Files (x86)\Microsoft Visual Studio %VCVER%\VC\vcvarsall.bat" %ARCH%
- cmd: cmake -S . -B build -G Ninja -DCMAKE_BUILD_TYPE=Release %CMakeArgs%
- sh: cmake -S . -B build -DCMAKE_BUILD_TYPE=Release ${CMakeArgs}
- cd build
- cmake --build . --config Release --target install
- cpack -C Release
artifacts:
- path: 'build/*.7z'
deploy:
  provider: GitHub
  auth_token:
    secure: XzGnVTRjZI2AuQzR5A6qPgZViAAbBVq7/VhM7O8kyTmjIkvUjH1RrwWiFLuinsus
  force_update: true
  on:
    APPVEYOR_REPO_TAG: true

