version: 1.12.{build}
pull_requests:
  do_not_increment_build_number: true
shallow_clone: true
environment:
  VCVER: 14.0
  ARCH: x64
  CMakeArgs: ""
install:
- cmd: >-
    appveyor DownloadFile https://github.com/ninja-build/ninja/releases/download/v1.8.2/ninja-win.zip -FileName ninja.zip

    7z x ninja.zip -oC:\projects\deps\ninja > nul

    set PATH=C:\projects\deps\ninja;%PATH%

    ninja --version
build_script:
- cmd: >-
    call "C:\Program Files (x86)\Microsoft Visual Studio %VCVER%\VC\vcvarsall.bat" %ARCH%

    mkdir build

    cd build

    cmake -G Ninja -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=install -DLSL_LSLBOOST_PATH=lslboost -DLSL_WINVER=0x0601 %CMakeArgs% ../

    cmake --build . --config Release --target install
artifacts:
- path: build/install
  name: lsl-liblsl_1.12.0-win_%ARCH%-msvc%VCVER%
deploy:
- provider: BinTray
  username: tstenner
  api_key:
    secure: Fo9tIQnGjVnCXB3euItvYrt85A5O9FPqq7LEpsdOuwW+eOg1rwA5Q1HLp4yWDXAl
  subject: labstreaminglayer
  version: 1.12
  repo: LSL
  package: liblsl
  override: true
