version: 1.12.{build}
pull_requests:
  do_not_increment_build_number: true
shallow_clone: true
environment:
  VCVER: 14.0
  ARCH: x64
  CMakeArgs: ""
  DODEPLOY: false
install:
- cmd: appveyor DownloadFile https://github.com/ninja-build/ninja/releases/download/v1.8.2/ninja-win.zip -FileName ninja.zip
- cmd: 7z x ninja.zip -oC:\projects\deps\ninja > nul
- cmd: set PATH=C:\projects\deps\ninja;%PATH%
- cmd: ninja --version
build_script:
- cmd: call "C:\Program Files (x86)\Microsoft Visual Studio %VCVER%\VC\vcvarsall.bat" %ARCH%
- mkdir build
- cd build
- cmd: cmake -G Ninja -DCMAKE_BUILD_TYPE=Release -DLSL_LSLBOOST_PATH=lslboost -DLSL_WINVER=0x0601 %CMakeArgs% ../
- cmake --build . --config Release --target install
- cpack
artifacts:
- path: 'build/*.7z'
  name: liblsl
deploy:
- provider: BinTray
  username: tstenner
  api_key:
    secure: Fo9tIQnGjVnCXB3euItvYrt85A5O9FPqq7LEpsdOuwW+eOg1rwA5Q1HLp4yWDXAl
  subject: labstreaminglayer
  version: 1.12
  repo: LSL
  package: liblsl
  publish: true
  override: true
  on:
    dodeploy: true
